---
slug: :worldon
depends:
  mikutter: 3.6.1
  plugin:
    - world
    - spell
    - gui
    - gtk
    - settings
    - command
    - extract
version: '1.0'
author: 
name: Worldon
description: mikutterでMastodonへ接続するworldプラグインです。
